### ISSUE TITLE
build error with install.sh -icd is it due to pip version

### ISSUE THREAD

**Issue by gggh000** [ROCmSoftwarePlatform/rocBLAS#1234]
Tried installing using install.sh -icd but not working because some pip related insatllation error. It complains pip version being old but when I checked both pip and pip3 they are newer.
It appears rocblas is fetching its own pip in build folder and that is being outdated?

`/root/ROCm-4.5/rocBLAS/build/release/virtualenv/bin/python3 -m pip install git+https://github.com/ROCmSoftwarePlatform/Tensile.git@0f6a6d1557868d6d563cb1edf167c32c2e34fda0

`

full log: 
```

install.sh -icd
....
-- Performing Test HAVE_gfx1030 - Success
/usr/bin/python3 -m venv /root/ROCm-4.5/rocBLAS/build/release/virtualenv --system-site-packages --clear
/root/ROCm-4.5/rocBLAS/build/release/virtualenv/bin/python3 -m pip install git+https://github.com/ROCmSoftwarePlatform/Tensile.git@0f6a6d1557868d6d563cb1edf167c32c2e34fda0
Collecting git+https://github.com/ROCmSoftwarePlatform/Tensile.git@0f6a6d1557868d6d563cb1edf167c32c2e34fda0
  Cloning https://github.com/ROCmSoftwarePlatform/Tensile.git (to 0f6a6d1557868d6d563cb1edf167c32c2e34fda0) to /tmp/pip-zvjx808b-build
  Complete output from command git show-ref 0f6a6d1557868d6d563cb1edf167c32c2e34fda0:
  
  ----------------------------------------
Command "git show-ref 0f6a6d1557868d6d563cb1edf167c32c2e34fda0" failed with error code 1 in /tmp/pip-zvjx808b-build
You are using pip version 9.0.3, however version 22.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
CMake Error at cmake/virtualenv.cmake:34 (message):
  1
Call Stack (most recent call first):
  CMakeLists.txt:276 (virtualenv_install)


-- Configuring incomplete, errors occurred!
See also "/root/ROCm-4.5/rocBLAS/build/release/CMakeFiles/CMakeOutput.log".
+ check_exit_code 1
+ ((  1 != 0  ))
+ exit 1
[root@localhost rocBLAS]# pip --version
pip 21.3.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
[root@localhost rocBLAS]# pip3 --version
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
pip 21.3.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
[root@localhost rocBLAS]# 

```

**Comment by mahmoodw** [comment]
Hello, there does seem to be some confusing version messages here. I would be interested in seeing what the following command produces:
/root/ROCm-4.5/rocBLAS/build/release/virtualenv/bin/python3 -m pip --version 

Then the following command may help:
/root/ROCm-4.5/rocBLAS/build/release/virtualenv/bin/python3 -m pip install --upgrade pip

So far I am unable to reproduce the error on my end.

**Comment by gggh000** [comment]
I can see above your recommendation returns 9.0.3 old version and I upgraded:
/root/ROCm-4.5/rocBLAS/build/release/virtualenv/bin/python3 -m pip install --upgrade pip

Now If I restart installation, it appears to be overwritten. It is back to 9.0.3, I am not sure when and how or when it is being overwritten when issuing "install -icd"

**Comment by gggh000** [comment]
Also on ubuntu build works but pip is still 9.0.3.
 I dont think error is due to pip version.
/root/ROCm-4.5/rocBLAS/build/release/virtualenv/bin/python3 -m pip --version

**Comment by gggh000** [comment]
I manually executed tensile build which is the point of failure. if i use /usr/bin/python3 it works fine, the python3 in the virtualenv is somehow failing the build:
[root@ixt-hq-178 pip-dhmcy29k-build]# python3 -m pip install git+https://github.com/ROCmSoftwarePlatform/Tensile.git@0f6a6d1557868d6d563cb1edf167c32c2e34fda0 2>&1 | tee pip.install.tensile.log
Collecting git+https://github.com/ROCmSoftwarePlatform/Tensile.git@0f6a6d1557868d6d563cb1edf167c32c2e34fda0
  Cloning https://github.com/ROCmSoftwarePlatform/Tensile.git (to revision 0f6a6d1557868d6d563cb1edf167c32c2e34fda0) to /tmp/pip-req-build-spnvi17t
  Running command git clone --filter=blob:none -q https://github.com/ROCmSoftwarePlatform/Tensile.git /tmp/pip-req-build-spnvi17t
  Running command git rev-parse -q --verify 'sha^0f6a6d1557868d6d563cb1edf167c32c2e34fda0'
  Running command git fetch -q https://github.com/ROCmSoftwarePlatform/Tensile.git 0f6a6d1557868d6d563cb1edf167c32c2e34fda0
  Running command git checkout -q 0f6a6d1557868d6d563cb1edf167c32c2e34fda0
  Resolved https://github.com/ROCmSoftwarePlatform/Tensile.git to commit 0f6a6d1557868d6d563cb1edf167c32c2e34fda0
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pyyaml in /usr/lib64/python3.6/site-packages (from Tensile==4.30.0) (3.12)
Collecting msgpack
  Downloading msgpack-1.0.3-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (299 kB)
Using legacy 'setup.py install' for Tensile, since package 'wheel' is not installed.
Installing collected packages: msgpack, Tensile
    Running setup.py install for Tensile: started
    Running setup.py install for Tensile: finished with status 'done'
Successfully installed Tensile-4.30.0 msgpack-1.0.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@ixt-hq-178 pip-dhmcy29k-build]# uname -r
5.6.13-0_fbk19_zion_6064_gabfd136bb69a
[root@ixt-hq-178 pip-dhmcy29k-build]# python3 -m pip install git+https://github.com/ROCmSoftwarePlatform/Tensile.git@0f6a6d1557868d6d563cb1edf167c32c2e34fda0 2>&1 | tee pip.install.tensile.log^C
[root@ixt-hq-178 pip-dhmcy29k-build]# which python3
/usr/bin/python3

**Comment by gggh000** [comment]
I manually issued python pip build of tensile and confirmed that after upgrading, it works. the cmake/virtualen_install needs following otherwise ended up using older pip and causing build failure of tensile thus rocblas.


[root@ixt-hq-178 rocBLAS]# /root/ROCm-4.5/rocBLAS/build/release/virtualenv/bin/python3 -m pip install --upgrade pip
Cache entry deserialization failed, entry ignored
Collecting pip
  Using cached https://files.pythonhosted.org/packages/a4/6d/6463d49a933f547439d6b5b98b46af8742cc03ae83543e4d7688c2420f8b/pip-21.3.1-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
Successfully installed pip-21.3.1
You are using pip version 21.3.1, however version 22.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@ixt-hq-178 rocBLAS]# /root/ROCm-4.5/rocBLAS/build/release/virtualenv/bin/python3 -m pip --version
pip 21.3.1 from /root/ROCm-4.5/rocBLAS/build/release/virtualenv/lib64/python3.6/site-packages/pip (python 3.6)
[root@ixt-hq-178 rocBLAS]# /root/ROCm-4.5/rocBLAS/build/release/virtualenv/bin/python3 -m pip install git+https://github.com/ROCmSoftwarePlatform/Tensile.git@0f6a6d1557868d6d563cb1edf167c32c2e34fda0 2>&1 | tee pip.install.tensile.log
Collecting git+https://github.com/ROCmSoftwarePlatform/Tensile.git@0f6a6d1557868d6d563cb1edf167c32c2e34fda0
  Cloning https://github.com/ROCmSoftwarePlatform/Tensile.git (to revision 0f6a6d1557868d6d563cb1edf167c32c2e34fda0) to /tmp/pip-req-build-qr7mgwng
  Running command git clone --filter=blob:none -q https://github.com/ROCmSoftwarePlatform/Tensile.git /tmp/pip-req-build-qr7mgwng
  Running command git rev-parse -q --verify 'sha^0f6a6d1557868d6d563cb1edf167c32c2e34fda0'
  Running command git fetch -q https://github.com/ROCmSoftwarePlatform/Tensile.git 0f6a6d1557868d6d563cb1edf167c32c2e34fda0
  Running command git checkout -q 0f6a6d1557868d6d563cb1edf167c32c2e34fda0
  Resolved https://github.com/ROCmSoftwarePlatform/Tensile.git to commit 0f6a6d1557868d6d563cb1edf167c32c2e34fda0
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: pyyaml in /usr/lib64/python3.6/site-packages (from Tensile==4.30.0) (3.12)
Requirement already satisfied: msgpack in /usr/local/lib64/python3.6/site-packages (from Tensile==4.30.0) (1.0.3)

**Comment by mahmoodw** [comment]
That is strange for sure. It seems like this issue could be specific to your environment. Have you been able to build successfully using your manual steps?

We will take this experience into consideration for future compatibility investigations.

**Comment by gggh000** [comment]
It seem hit and miss problem. in cmake/virtualenv_install add command upgrade pip just before install to make it work.

**Comment by mahmoodw** [comment]
This is useful information. Is it okay if we close this issue?

**Comment by gggh000** [comment]
I dont think so. I put all effort in identifying the problem for you but you are not taking fix?

**Comment by amcamd** [comment]
@gggh000  Thank you for identifying the problem and providing the fix. The fix is implemented in the rocBLAS develop branch in commit 7f6c2bbdd (April 8). Building with the following should avoid the error "You are using pip version 21.3.1, however version 22.0.3 is available."
```
./install.sh -icd --upgrade_tensile_venv_pip
```

**Comment by amdsc21** [comment]
@amcamd The errors are still there.

rocBLAS/build/release/virtualenv/bin/python3 -m pip install git+https://github.com/ROCmSoftwarePlatform/Tensile.git@f7b4fe5f53bea220f3e02edf603971f4a1aafc3c
Collecting git+https://github.com/ROCmSoftwarePlatform/Tensile.git@f7b4fe5f53bea220f3e02edf603971f4a1aafc3c
  Cloning https://github.com/ROCmSoftwarePlatform/Tensile.git (to f7b4fe5f53bea220f3e02edf603971f4a1aafc3c) to /tmp/pip-1sdew3m1-build
  Complete output from command git show-ref f7b4fe5f53bea220f3e02edf603971f4a1aafc3c:

  ----------------------------------------
Command "git show-ref f7b4fe5f53bea220f3e02edf603971f4a1aafc3c" failed with error code 1 in /tmp/pip-1sdew3m1-build
You are using pip version 9.0.3, however version 22.0.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
CMake Error at cmake/virtualenv.cmake:46 (message):
  1
Call Stack (most recent call first):
  CMakeLists.txt:158 (virtualenv_install)


-- Configuring incomplete, errors occurred!

**Comment by amdsc21** [comment]
env: 

CentOS Stream release 8
NAME="CentOS Stream"
VERSION="8"

ROCM 5.1.0

**Comment by cgmb** [comment]
It's hard to tell what's going wrong from just that snippet. @amdsc21, could you please provide a full log of the build output?

You seem to still have an old version of pip. Just to confirm, you are passing  `--upgrade_tensile_venv_pip` when building rocBLAS? Is the pip upgrade failing?

**Comment by amdsc21** [comment]
It looks --upgrade_tensile_venv_pip didn't trigger the upgrade?

**Comment by cgmb** [comment]
Thanks. It seems that this option was broken when resolving the merge conflict between 461bf379f04482533122494adc8cd009b526b6d9 and 0806ecd41a756f80b5d010cd6c754b067ee989e1.

**Comment by TorreZuk** [comment]
Sorry it looks like a bad merge took out the fix @amcamd , later commit requires cmake_common_options needs to be appended to now.

**Comment by amdsc21** [comment]
Thanks for the confirmation @cgmb @TorreZuk

**Comment by cgmb** [comment]
@amcamd made a fix today in 9144f85e5eabf6eabbb97093cfe4103dc7d2fa9b. @amdsc21, I believe it should work for you now if you pull the latest changes on `develop` branch and retry.

**Comment by gggh000** [comment]
i will take a look, thx

**Comment by gggh000** [comment]
i checked out rocm-swplat/develop and now seeing different error:

git branch
* (HEAD detached at rocm-swplat/develop)
git log
commit 505c957c1250bb35e057bee129bdf70f70ca0eb5 (HEAD, rocm-swplat/develop)
Author: Ruban Kumar <92320771+rkamd@users.noreply.github.com>
Date:   Fri Apr 22 13:55:54 2022 -0400

    Hotfix for build error when compiled with '--clients-only' option (#1197) (#1203)
    
    * Updated internal includes list for clients directory


./install.sh -icd --upgrade_tensile_venv_pip
....
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- hip::amdhip64 is SHARED_LIBRARY
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS - Success
-- hip::amdhip64 is SHARED_LIBRARY
-- Using AMDGPU_TARGETS: gfx803;gfx900;gfx906:xnack-;gfx908:xnack-;gfx90a:xnack+;gfx90a:xnack-;gfx1010;gfx1012;gfx1030
-- OS: centos 8
-- Tensile script: /root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib64/python3.6/site-packages/Tensile/bin/TensileCreateLibrary
-- Tensile_CREATE_COMMAND: /root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib64/python3.6/site-packages/Tensile/bin/TensileCreateLibrary;--merge-files;--separate-architectures;--no-short-file-names;--no-library-print-debug;--code-object-version=V3;--cxx-compiler=hipcc;--library-format=msgpack;--architecture=gfx803_gfx900_gfx906:xnack-_gfx908:xnack-_gfx90a:xnack+_gfx90a:xnack-_gfx1010_gfx1012_gfx1030;/root/ROCm-5.1/rocBLAS/library/src/blas3/Tensile/Logic/asm_full;/root/ROCm-5.1/rocBLAS/build/release/Tensile;HIP
-- Tensile_MANIFEST_FILE_PATH: /root/ROCm-5.1/rocBLAS/build/release/Tensile/library/TensileManifest.txt
'/root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib64/python3.6/site-packages/Tensile/bin/TensileCreateLibrary' '--merge-files' '--separate-architectures' '--no-short-file-names' '--no-library-print-debug' '--code-object-version=V3' '--cxx-compiler=hipcc' '--library-format=msgpack' '--architecture=gfx803_gfx900_gfx906:xnack-_gfx908:xnack-_gfx90a:xnack+_gfx90a:xnack-_gfx1010_gfx1012_gfx1030' '/root/ROCm-5.1/rocBLAS/library/src/blas3/Tensile/Logic/asm_full' '/root/ROCm-5.1/rocBLAS/build/release/Tensile' 'HIP' '--generate-manifest-and-exit'
Traceback (most recent call last):
  File "/root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib64/python3.6/site-packages/Tensile/bin/TensileCreateLibrary", line 25, in <module>
    from Tensile.TensileCreateLibrary import TensileCreateLibrary
ModuleNotFoundError: No module named 'Tensile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib64/python3.6/site-packages/Tensile/bin/TensileCreateLibrary", line 32, in <module>
    from Tensile.TensileCreateLibrary import TensileCreateLibrary
  File "/root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib/python3.6/site-packages/Tensile/TensileCreateLibrary.py", line 30, in <module>
    from . import LibraryIO
  File "/root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib/python3.6/site-packages/Tensile/LibraryIO.py", line 23, in <module>
    from .SolutionStructs import Solution, ProblemSizes, ProblemType
  File "/root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib/python3.6/site-packages/Tensile/SolutionStructs.py", line 35, in <module>
    from .CustomKernels import isCustomKernelConfig
  File "/root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib/python3.6/site-packages/Tensile/CustomKernels.py", line 24, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
CMake Error at build/release/virtualenv/cmake/TensileConfig.cmake:251 (message):
  Error creating Tensile library: 1
Call Stack (most recent call first):
  library/src/CMakeLists.txt:79 (TensileCreateLibraryFiles)


-- Configuring incomplete, errors occurred!
See also "/root/ROCm-5.1/rocBLAS/build/release/CMakeFiles/CMakeOutput.log".
+ check_exit_code 1
+ ((  1 != 0  ))
+ exit 1

This is a different error so I filed https://github.com/ROCmSoftwarePlatform/rocBLAS/issues/1244

**Comment by gggh000** [comment]
Can you do a full installation test when fix made before updating here 
./install.sh -icd
? It appears one thing is fixed and it introduces other error.

**Comment by amdsc21** [comment]
@gggh000 Are you using CentOS or RHEL? It looks ubuntu 20.04 is fine with me. If you are using CentOS/RHEL, what is your version please?

**Comment by gggh000** [comment]
using centos 8 stream

**Comment by amdsc21** [comment]
@gggh000 It looks Centos 8 stream isn't supported. However, you can install latest rocm5.1.1 (rocblas5.1.1 etc) on centos 8 stream, https://repo.radeon.com/rocm/yum/5.1.1/main/

Not a rocBLAS developer. But for the parts I use, rocblas5.1.1 is very fast, which has the same performance as latest build. I do try latest build on a few machines with different GPUs. :-)

**Comment by gggh000** [comment]
please find the error and fix it and also test full installation. why you always trying to find an easy exit opportunistically? It just happened to be centos 8 and I am not going to switch to encounter another distro like ubuntu to run into another problem. clearly build instruction does not say centos 8 supported and simply it is linux.

Why you always try to find an exit instead of fix like below??

[mahmoodw](https://github.com/mahmoodw) commented [on Mar 3](https://github.com/ROCmSoftwarePlatform/rocBLAS/issues/1234#issuecomment-1058316162)
This is useful information. Is it okay if we close this issue?

@gggh000
Author
gggh000 commented on Mar 3
I dont think so. I put all effort in identifying the problem for you but you are not taking fix?

**Comment by gggh000** [comment]
All of the following is failing spectacularly, every way possible. There is some very poor code check in happening that is breaking things apart:
I am talking about all those below builds that are documented and supported, supposedly:

**FAIL TYPE #1**
./install.sh -id --no-tensile:
Fails
...
Extra Packages for Enterprise Linux 8 - x86_64  107 kB/s |  18 kB     00:00
Extra Packages for Enterprise Linux 8 - x86_64   17 MB/s |  11 MB     00:00
Extra Packages for Enterprise Linux Modular 8 - 8.0 kB/s |  18 kB     00:02
Extra Packages for Enterprise Linux 8 - Next -   55 kB/s |  19 kB     00:00
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**FAIL TYPE #2 with **

./install.sh -icd --no-tensile
[  2%] Built target rocblas-common
[  3%] Building Fortran object clients/CMakeFiles/rocblas_fortran.dir/__/library/include/rocblas_module.f90.o
Traceback (most recent call last):
  File "../common/rocblas_gentest.py", line 12, in <module>
    from yaml import CLoader as Loader
ModuleNotFoundError: No module named 'yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../common/rocblas_gentest.py", line 14, in <module>
    from yaml import Loader
ModuleNotFoundError: No module named 'yaml'
make[2]: *** [clients/gtest/CMakeFiles/rocblas-test-data.dir/build.make:117: clients/staging/rocblas_gtest.data] Error 1
make[1]: *** [CMakeFiles/Makefile2:769: clients/gtest/CMakeFiles/rocblas-test-data.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  3%] Built target rocblas_proto_templates
[  3%] Built target rocblas_fortran
make: *** [Makefile:155: all] Error 2
+ check_exit_code 2
+ ((  2 != 0  ))
+ exit 2

**FAIL TYPE #3**

**Comment by TorreZuk** [comment]
Unfortunately Centos Stream 8 is not one of the ROCm supported OS (System Requirements) as listed at https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.1.1/page/Overview_of_ROCm_Installation_Methods.html
While I have migrated Centos 8 with ROCm 5.1 installed to Centos Stream 8 and rebuilt rocBLAS 5.1.1 successfully with the --upgrade_tensile_venv_pip install.sh flag, I too have seen that package management isn't supported well on Centos Stream 8 and so it can easily be broken with updates.  If you don't want to invest further in an unsupported OS and be exposed to the corresponding build issues, I would suggest switching to a supported OS. Your desire for Centos Stream 8 support has been noted.

If you wish to continue with Centos Stream 8 manually installing all package dependencies and python modules before running the script may be the way forward.   In the one issue you indicate that you get "--skip-broken" message, and that indicates your package dependencies are already messed up, which could break further progress.  Note there are both OS package and python modules related to yaml (for packages see the line "python3" "python3*-PyYAML" "python3-virtualenv" in install.sh).  Those should be first resolved so that no package issues exist. Site installed python modules are included in the rocBLAS python virtual env invocation.   A list of python modules that you have installed, and their versions, may help diagnose your build issue.   If you use the updated rocBLAS issue template it advises on capturing more system details which can be attached in an environment log file.     I suggest we collapse all your separate github issues into this single issue, as they all appear to stem from broken Centos Stream 8 support.

Thanks for your feedback.

**Comment by cgmb** [comment]
There's a number of build problems would be easier to deal with if there was a way to build rocBLAS without using pip or virtualenv. This is one of a slew of feature requests I have for rocBLAS that I've been very slow to make tickets for, but I'll begin filing them soon.

**Comment by TorreZuk** [comment]
--upgrade_tensile_venv_pip solves the particular pip version problem on supported OS.  In the future new OS should be supported but closing this ticket as the issue was resolved on supported OS and information is stale and no further feedback received.
