### ISSUE TITLE
rocm5.1 installation fails due to tensile error

### ISSUE THREAD

**Issue by gggh000** [ROCmSoftwarePlatform/rocBLAS#1246]
Checked out whole rocm5.1 code and then checked out develop branch due to 1234 fix. Now tensile related error is occurring if built with tensile support by default:
```

[root@ rocBLAS]# ./install.sh -icd --upgrade_tensile_venv_pip

-- Check for working C compiler: /opt/rocm/bin/hipcc
-- Check for working C compiler: /opt/rocm/bin/hipcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- hip::amdhip64 is SHARED_LIBRARY
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS - Success
-- hip::amdhip64 is SHARED_LIBRARY
-- Using AMDGPU_TARGETS: gfx803;gfx900;gfx906:xnack-;gfx908:xnack-;gfx90a:xnack+;gfx90a:xnack-;gfx1010;gfx1012;gfx1030
-- OS: centos 8
-- Tensile script: /root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib64/python3.6/site-packages/Tensile/bin/TensileCreateLibrary
-- Tensile_CREATE_COMMAND: /root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib64/python3.6/site-packages/Tensile/bin/TensileCreateLibrary;--merge-files;--separate-architectures;--no-short-file-names;--no-library-print-debug;--code-object-version=V3;--cxx-compiler=hipcc;--library-format=msgpack;--architecture=gfx803_gfx900_gfx906:xnack-_gfx908:xnack-_gfx90a:xnack+_gfx90a:xnack-_gfx1010_gfx1012_gfx1030;/root/ROCm-5.1/rocBLAS/library/src/blas3/Tensile/Logic/asm_full;/root/ROCm-5.1/rocBLAS/build/release/Tensile;HIP
-- Tensile_MANIFEST_FILE_PATH: /root/ROCm-5.1/rocBLAS/build/release/Tensile/library/TensileManifest.txt
'/root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib64/python3.6/site-packages/Tensile/bin/TensileCreateLibrary' '--merge-files' '--separate-architectures' '--no-short-file-names' '--no-library-print-debug' '--code-object-version=V3' '--cxx-compiler=hipcc' '--library-format=msgpack' '--architecture=gfx803_gfx900_gfx906:xnack-_gfx908:xnack-_gfx90a:xnack+_gfx90a:xnack-_gfx1010_gfx1012_gfx1030' '/root/ROCm-5.1/rocBLAS/library/src/blas3/Tensile/Logic/asm_full' '/root/ROCm-5.1/rocBLAS/build/release/Tensile' 'HIP' '--generate-manifest-and-exit'
Traceback (most recent call last):
  File "/root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib64/python3.6/site-packages/Tensile/bin/TensileCreateLibrary", line 25, in <module>
    from Tensile.TensileCreateLibrary import TensileCreateLibrary
ModuleNotFoundError: No module named 'Tensile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib64/python3.6/site-packages/Tensile/bin/TensileCreateLibrary", line 32, in <module>
    from Tensile.TensileCreateLibrary import TensileCreateLibrary
  File "/root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib/python3.6/site-packages/Tensile/TensileCreateLibrary.py", line 30, in <module>
    from . import LibraryIO
  File "/root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib/python3.6/site-packages/Tensile/LibraryIO.py", line 23, in <module>
    from .SolutionStructs import Solution, ProblemSizes, ProblemType
  File "/root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib/python3.6/site-packages/Tensile/SolutionStructs.py", line 35, in <module>
    from .CustomKernels import isCustomKernelConfig
  File "/root/ROCm-5.1/rocBLAS/build/release/virtualenv/lib/python3.6/site-packages/Tensile/CustomKernels.py", line 24, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
CMake Error at build/release/virtualenv/cmake/TensileConfig.cmake:251 (message):
  Error creating Tensile library: 1
Call Stack (most recent call first):
  library/src/CMakeLists.txt:79 (TensileCreateLibraryFiles)


-- Configuring incomplete, errors occurred!
See also "/root/ROCm-5.1/rocBLAS/build/release/CMakeFiles/CMakeOutput.log".
+ check_exit_code 1
+ ((  1 != 0  ))
+ exit 1
``
```

**Comment by TorreZuk** [comment]
Merging this into issue #1234 as closely related.   As I expect it relates to OS, as stated in that issue:  "Unfortunately Centos Stream 8 is not one of the ROCm supported OS (System Requirements) as listed at https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.1.1/page/Overview_of_ROCm_Installation_Methods.html  " If details on python modules installed are provided in that issue we can advise on workarounds but for now closing these issues as duplicates.
