### ISSUE TITLE
[Bug]: Is latest dev branch compatible with pytorch, ROCm5.4.1?

### ISSUE THREAD

**Issue by mindest** [ROCmSoftwarePlatform/rocBLAS#1302]
### Describe the bug
I install rocBLAS from source develop branch. After installation, it complains when importing torch that

    ImportError: librocblas.so.0: cannot open shared object file: No such file or directory

### To Reproduce
* rocBLAS version: built from source (commit hash: 967e8e00917b20cabb402c3c9dee8582fcf0278b)
* docker image: `rocm/pytorch:rocm5.4.1_ubuntu20.04_py3.7_pytorch_1.12.1`

```bash
git clone https://github.com/ROCmSoftwarePlatform/rocBLAS
cd rocBLAS
# git checkout 967e8e00917b20cabb402c3c9dee8582fcf0278b
./install -idc
python -c "import torch"
```

### Expected behavior
torch is exported with no warning/error.

### Log
    root@host# python -c "import torch"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/conda/lib/python3.7/site-packages/torch/__init__.py", line 202, in <module>
        from torch._C import *  # noqa: F403
    ImportError: librocblas.so.0: cannot open shared object file: No such file or directory

### Environment

| Hardware | description |
|-----|-----|
| CPU | AMD EPYC 7V12 64-Core Processor |
| GPU | AMD Instinct MI250X/MI250 |

| Software | version |
|-----|-----|
| rocm-core | 5.4.1.50401-84~20.04 |
| rocblas | 3.1.0-967e8e00 |

Please see the attachment for more info if necessary: [environment.txt](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/11195987/environment.txt)

**Comment by mindest** [comment]
No, thanks. Closing.
