### ISSUE TITLE
Build failed with ROCm 2.5 & 2.3

### ISSUE THREAD

**Issue by wormwang** [ROCmSoftwarePlatform/rocBLAS#576]
### What is the expected behavior
-  

### What actually happens
-  
error out when make install , may related to https://github.com/ROCm-Developer-Tools/HIP/issues/485

### How to reproduce
- 
rocm repo rocm-2.3

make 
make install , on ROCm 2.3
then error out

### Environment
| Hardware | description |
|-----|-----|
| GPU | device string |
amd vega
| CPU | device string |

| Software | version |
ROCm 2.3

pls reopen it
env: rocm-2.3 , Ubuntu 18.04

meet err when make rocBLAS

~/ROCm/rocBLAS/release# make install
Scanning dependencies of target Tensile
[ 3%] Building CXX object library/src/CMakeFiles/Tensile.dir///Tensile/Kernels.cpp.o
Stack dump:
0. Program arguments: /opt/rocm/hcc/bin/llc -mtriple amdgcn-amd-amdhsa -mcpu=gfx900 -mattr=-code-object-v3 -O2 -amdgpu-function-calls=0 -filetype=obj -o /tmp/tmp.r7iSdMgsmb/kernel-gfx900.hsaco.isabin /tmp/tmp.r7iSdMgsmb/kernel-gfx900.hsaco.opt.bc

    Running pass 'CallGraph Pass Manager' on module '/tmp/tmp.r7iSdMgsmb/kernel-gfx900.hsaco.opt.bc'.
    Running pass 'Prologue/Epilogue Insertion & Frame Finalization' on function '@Cijk_Ailk_Bjlk_4xi8BH_MT96x128x16_APM1_AF0EM1_AF1EM1_AMAS2_ASEM1_BL0_DTL0_EPS0_FL0_GRVW2_GSU1_ISA000_IU1_K1_KLS_LPA0_LPB0_LDL1_MGWVW1_NLCA3_NLCB1_PK0_PGR1_PLR1_SU32_SNLL0_TT6_8_USFGRO0_VAW1_VW2_WG16_16_1_WGM8'
    /opt/rocm/hcc/bin/llc(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x40)[0xaaaac00b1ee8]
    /opt/rocm/hcc/bin/clamp-device: line 250: 54708 Segmentation fault (core dumped) $LLC -mtriple amdgcn-amd-amdhsa -mcpu=$AMDGPU_TARGET $CODE_OBJECT_FORMAT $KMOPTLLC -amdgpu-function-calls=$AMDGPU_FUNC_CALLS -filetype=obj -o $2.isabin $2.opt.bc
    Generating AMD GCN kernel failed in llc for target: gfx900
    Error: hc-kernel-assemble[175]: failed with status -1
    clang-9: error: HC assembler command failed with exit code 255 (use -v to see invocation)
    library/src/CMakeFiles/Tensile.dir/build.make:62: recipe for target 'library/src/CMakeFiles/Tensile.dir///Tensile/Kernels.cpp.o' failed
    make[2]: *** [library/src/CMakeFiles/Tensile.dir///Tensile/Kernels.cpp.o] Error 255
    CMakeFiles/Makefile2:142: recipe for target 'library/src/CMakeFiles/Tensile.dir/all' failed
    make[1]: *** [library/src/CMakeFiles/Tensile.dir/all] Error 2
    Makefile:151: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by wormwang** [comment]
| Software | version |
ROCm 2.5

pls reopen it
env: rocm-2.5 , Ubuntu 18.04, gcc 7.4.0

meet err when cmake rocBLAS

In file included from /home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/Tensile/TensileTypes.h:29:
/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/Tensile/tensile_bfloat16.h:65:9: warning: type definition in a constexpr function is a C++14 extension [-Wc++14-extensions]
        union
        ^
/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/Tensile/tensile_bfloat16.h:69:11: warning: variable declaration in a constexpr function is a C++14 extension [-Wc++14-extensions]
        } u = {uint32_t(data) << 16};
          ^
/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/Tensile/tensile_bfloat16.h:76:9: warning: type definition in a constexpr function is a C++14 extension [-Wc++14-extensions]
        union
        ^
/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/Tensile/tensile_bfloat16.h:80:11: warning: variable declaration in a constexpr function is a C++14 extension [-Wc++14-extensions]
        } u = {f};
          ^
/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/Tensile/tensile_bfloat16.h:81:9: warning: use of this statement in a constexpr function is a C++14 extension [-Wc++14-extensions]
        if(~u.int32 & 0x7f800000)
        ^
5 warnings generated.
Stack dump:
0.	Program arguments: /opt/rocm-2.3.0613/hcc/bin/llc -mtriple amdgcn-amd-amdhsa -mcpu=gfx900 -mattr=-code-object-v3 -O2 -amdgpu-function-calls=0 -filetype=obj -o /tmp/tmp.Lt7NBI7Rnf/kernel-gfx900.hsaco.isabin /tmp/tmp.Lt7NBI7Rnf/kernel-gfx900.hsaco.opt.bc 
1.	Running pass 'CallGraph Pass Manager' on module '/tmp/tmp.Lt7NBI7Rnf/kernel-gfx900.hsaco.opt.bc'.
2.	Running pass 'Prologue/Epilogue Insertion & Frame Finalization' on function '@Cijk_Ailk_Bjlk_4xi8BH_MT96x128x16_SE_APM1_AF0EM1_AF1EM1_AMAS2_ASEM1_BL0_DTL0_EPS0_FL0_GRVW2_GSU1_ISA000_IU1_K1_KLS_LPA0_LPB0_LDL1_MGWVW1_NLCA3_NLCB1_PK0_PGR1_PLR1_RK0_SU32_SNLL0_TT6_8_USFGRO0_VAW1_VW2_WG16_16_1_WGM8'
/opt/rocm-2.3.0613/hcc/bin/llc(_ZN4llvm3sys15PrintStackTraceERNS_11raw_ostreamE+0x40)[0xaaaad05c5440]
/opt/rocm-2.3.0613/hcc/bin/clamp-device: line 250: 61335 Segmentation fault      (core dumped) $LLC -mtriple amdgcn-amd-amdhsa -mcpu=$AMDGPU_TARGET $CODE_OBJECT_FORMAT $KMOPTLLC -amdgpu-function-calls=$AMDGPU_FUNC_CALLS -filetype=obj -o $2.isabin $2.opt.bc
Generating AMD GCN kernel failed in llc for target: gfx900
clang-9: error: linker command failed with exit code 22 (use -v to see invocation)
Traceback (most recent call last):
  File "/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/virtualenv/lib/python3.6/site-packages/Tensile/Common.py", line 1069, in apply_print_exception
    return func(*args)
  File "/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/virtualenv/lib/python3.6/site-packages/Tensile/TensileCreateLibrary.py", line 135, in buildSourceCodeObjectFile
    subprocess.check_call(linkArgs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/rocm/bin/hcc', '', '-hc', '-std=c++amp', '-L/opt/rocm-2.3.0613/hcc/lib', '-Wl,--rpath=/opt/rocm-2.3.0613/hcc/lib', '-ldl', '-lm', '-lpthread', '-lhc_am', '-Wl,--whole-archive', '-lmcwamp', '-Wl,--no-whole-archive', '-shared', '-fPIC', '', '-amdgpu-target=gfx803', '-amdgpu-target=gfx900', '-amdgpu-target=gfx906', '/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/code_object_tmp/Kernels.o', '-shared', '-o', '/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/code_object_tmp/Kernels.so']' returned non-zero exit status 22.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/virtualenv/lib/python3.6/site-packages/Tensile/Common.py", line 1069, in apply_print_exception
    return func(*args)
  File "/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/virtualenv/lib/python3.6/site-packages/Tensile/TensileCreateLibrary.py", line 135, in buildSourceCodeObjectFile
    subprocess.check_call(linkArgs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/rocm/bin/hcc', '', '-hc', '-std=c++amp', '-L/opt/rocm-2.3.0613/hcc/lib', '-Wl,--rpath=/opt/rocm-2.3.0613/hcc/lib', '-ldl', '-lm', '-lpthread', '-lhc_am', '-Wl,--whole-archive', '-lmcwamp', '-Wl,--no-whole-archive', '-shared', '-fPIC', '', '-amdgpu-target=gfx803', '-amdgpu-target=gfx900', '-amdgpu-target=gfx906', '/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/code_object_tmp/Kernels.o', '-shared', '-o', '/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/code_object_tmp/Kernels.so']' returned non-zero exit status 22.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/virtualenv/bin/TensileCreateLibrary", line 10, in <module>
    sys.exit(TensileCreateLibrary())
  File "/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/virtualenv/lib/python3.6/site-packages/Tensile/TensileCreateLibrary.py", line 1003, in TensileCreateLibrary
    kernelWriterSource, kernelWriterAssembly)
  File "/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/virtualenv/lib/python3.6/site-packages/Tensile/TensileCreateLibrary.py", line 309, in writeSolutionsAndKernels
    codeObjectFiles += buildSourceCodeObjectFiles(kernelFiles, kernels + kernelsBetaOnly, outputPath)
  File "/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/virtualenv/lib/python3.6/site-packages/Tensile/TensileCreateLibrary.py", line 148, in buildSourceCodeObjectFiles
    method=lambda x: x.starmap)
  File "/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/virtualenv/lib/python3.6/site-packages/Tensile/Common.py", line 1139, in ParallelMap
    rv = mapFunc(function, objects)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
subprocess.CalledProcessError: Command '['/opt/rocm/bin/hcc', '', '-hc', '-std=c++amp', '-L/opt/rocm-2.3.0613/hcc/lib', '-Wl,--rpath=/opt/rocm-2.3.0613/hcc/lib', '-ldl', '-lm', '-lpthread', '-lhc_am', '-Wl,--whole-archive', '-lmcwamp', '-Wl,--no-whole-archive', '-shared', '-fPIC', '', '-amdgpu-target=gfx803', '-amdgpu-target=gfx900', '-amdgpu-target=gfx906', '/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/code_object_tmp/Kernels.o', '-shared', '-o', '/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/code_object_tmp/Kernels.so']' returned non-zero exit status 22.
CMake Error at release/virtualenv/cmake/TensileConfig.cmake:87 (message):
  Error generating kernels
Call Stack (most recent call first):
  library/src/CMakeLists.txt:41 (TensileCreateLibrary)


-- Configuring incomplete, errors occurred!
See also "/home/motech/rocm2.5/rocBLAS-master/rocBLAS/release/CMakeFiles/CMakeOutput.log".

**Comment by wormwang** [comment]
build successful with hcc of rocm2.4
